// 測驗題庫。每題：question、options（4 選 1）、answer（正解索引）、explanation、
// articleSlug（答錯時導向的知識庫文章，可省略）。
// 題庫題數 > questionsPerRound，每輪隨機抽題增加重玩價值。

export const masterBank = {
  id: 'master',
  title: '金吉拉大師',
  questionsPerRound: 10,
  ranks: [
    { min: 90, title: '金吉拉大師', emoji: '👑', comment: '太強了！你對金吉拉的了解已是大師級！' },
    { min: 70, title: '資深貓奴', emoji: '🎓', comment: '相當不錯！再多讀幾篇文章就能封王。' },
    { min: 40, title: '見習鏟屎官', emoji: '📖', comment: '有基礎了！到知識庫進修一下吧。' },
    { min: 0, title: '路過的好奇貓', emoji: '🐾', comment: '沒關係，每位大師都是從好奇開始的！' },
  ],
  questions: [
    {
      id: 'm1',
      question: '金吉拉貓在品種分類上，其實是哪個家族的一員？',
      options: ['暹羅貓', '波斯貓', '英國短毛貓', '布偶貓'],
      answer: 1,
      explanation: '金吉拉是波斯貓家族中的銀白色品系，並非獨立品種。',
      articleSlug: 'what-is-chinchilla-cat',
    },
    {
      id: 'm2',
      question: '被視為現代金吉拉基因基礎的貓咪 Chinnie 出生於哪一年？',
      options: ['1882 年', '1920 年', '1950 年', '1994 年'],
      answer: 0,
      explanation: '1882 年出生的母貓 Chinnie 被視為現代金吉拉的基因基礎；1894 年金吉拉在倫敦水晶宮貓展亮相。',
      articleSlug: 'what-is-chinchilla-cat',
    },
    {
      id: 'm3',
      question: '「Chinchilla」這個名字的靈感來自哪種動物？',
      options: ['北極狐', '南美洲的絨鼠（龍貓）', '銀狐', '雪貂'],
      answer: 1,
      explanation: '因毛色神似南美絨鼠柔軟的銀灰毛皮而得名，所以英文要說 Chinchilla Persian 才不會被誤會是龍貓。',
      articleSlug: 'what-is-chinchilla-cat',
    },
    {
      id: 'm4',
      question: '金吉拉招牌的 Tipped 毛色，毛尖著色比例大約是多少？',
      options: ['約 1/8', '約 1/3', '約 1/2', '整根毛都有色'],
      answer: 0,
      explanation: '金吉拉毛尖僅約 1/8 帶色，遠看像撒了銀霜；著色到 1/3 的稱為 Shaded（漸層）。',
      articleSlug: 'chinchilla-vs-silver-shaded',
    },
    {
      id: 'm5',
      question: '在台灣，寵物市場常說的「銀漸層」大多是指哪種貓？',
      options: ['金吉拉的別名', '英國短毛貓的銀漸層色', '俄羅斯藍貓', '銀色的美國短毛貓'],
      answer: 1,
      explanation: '台灣語境的「銀漸層」多指英短銀漸層——短毛、鼻樑較挺，跟長毛的金吉拉是不同品種。判斷重點：毛長。',
      articleSlug: 'chinchilla-vs-silver-shaded',
    },
    {
      id: 'm6',
      question: '金吉拉最經典的眼睛顏色是？',
      options: ['琥珀色', '翠綠或藍綠色', '深藍色', '異色瞳'],
      answer: 1,
      explanation: '金吉拉以翠綠、藍綠色的大圓眼聞名，還配有天生的黑色「眼線」。',
      articleSlug: 'appearance-features',
    },
    {
      id: 'm7',
      question: '金吉拉眼周的黑色「眼線」是怎麼來的？',
      options: ['飼主幫牠畫的', '天生的色素表現', '生病的徵兆', '只有公貓才有'],
      answer: 1,
      explanation: '眼線是毛尖色素在眼周皮膚的天生表現，同樣的深色描邊也出現在鼻外圈與唇線，是品種標誌。',
      articleSlug: 'appearance-features',
    },
    {
      id: 'm8',
      question: '金吉拉的鼻子是什麼顏色？',
      options: ['黑色', '磚紅色', '粉白色', '深棕色'],
      answer: 1,
      explanation: '磚紅色的鼻子配上深色外圈描邊，是金吉拉的特徵之一。',
      articleSlug: 'appearance-features',
    },
    {
      id: 'm9',
      question: '下列哪一項最符合金吉拉的個性？',
      options: ['活潑好動、愛飛簷走壁', '溫順安靜、喜歡陪伴', '警戒心強、不親人', '極度黏人、離不開飼主'],
      answer: 1,
      explanation: '金吉拉承襲波斯家族的沉穩：溫順、安靜、慢熱，喜歡靜靜陪伴而不過度黏人。',
      articleSlug: 'what-is-chinchilla-cat',
    },
    {
      id: 'm10',
      question: '金吉拉幼貓的毛色通常有什麼特徵？',
      options: ['跟成貓完全一樣', '毛尖色較深、甚至帶條紋，長大才變淺', '全身純白無雜色', '出生時是黑色的'],
      answer: 1,
      explanation: '幼貓毛尖色較深、可能帶明顯條紋，約一歲後才呈現成貓的銀霜質感，挑幼貓時可參考父母毛色。',
      articleSlug: 'appearance-features',
    },
    {
      id: 'm11',
      question: '金吉拉的平均壽命大約是？',
      options: ['5–8 年', '8–10 年', '12–15 年', '20 年以上'],
      answer: 2,
      explanation: '金吉拉平均壽命約 12–15 年，透過定期健檢與良好照顧可以陪伴更久。',
      articleSlug: 'health-overview',
    },
    {
      id: 'm12',
      question: '金吉拉家族最需要注意的遺傳疾病是？',
      options: ['髖關節發育不良', '多囊性腎病（PKD）', '心絲蟲', '糖尿病'],
      answer: 1,
      explanation: '波斯家族帶有多囊性腎病（PKD）的遺傳傾向，購買前要求 PKD 基因檢測報告是關鍵把關。',
      articleSlug: 'health-overview',
    },
    {
      id: 'm13',
      question: '金吉拉常見的毛色不包括下列哪一種？',
      options: ['銀色（Silver）', '金色（Golden）', '藍金色（Blue Golden）', '純黑色（Solid Black）'],
      answer: 3,
      explanation: '金吉拉的毛色核心是底毛淺色＋毛尖著色的漸層，銀色最經典、金色較少、藍色系稀有，沒有純黑色。',
      articleSlug: 'appearance-features',
    },
    {
      id: 'm14',
      question: '關於金吉拉的居家環境，下列敘述何者正確？',
      options: ['需要大量垂直跳台空間', '不擅跳高，垂直空間需求低', '必須養在戶外', '喜歡潮濕的環境'],
      answer: 1,
      explanation: '金吉拉不擅長爬高跳遠，比起跳台更愛沙發與窗台；環境重點反而是乾燥通風。',
      articleSlug: 'newbie-checklist',
    },
  ],
}

export const careExamBank = {
  id: 'careExam',
  title: '金吉拉飼養考試',
  questionsPerRound: 10,
  ranks: [
    { min: 90, title: '五星級鏟屎官', emoji: '⭐', comment: '你家貓咪太幸福了！飼養知識滿分！' },
    { min: 70, title: '合格飼主', emoji: '✅', comment: '基本功扎實，細節再加強就完美了。' },
    { min: 40, title: '實習飼主', emoji: '🧑‍🎓', comment: '先別急著接貓，把飼養文章讀完再來一輪！' },
    { min: 0, title: '貓咪體驗生', emoji: '🐱', comment: '從知識庫的飼養指南開始打好基礎吧！' },
  ],
  questions: [
    {
      id: 'c1',
      question: '下列哪種食物對貓咪是明確有毒的？',
      options: ['蒸熟的雞胸肉', '洋蔥與大蒜', '貓用化毛膏', '無調味白身魚'],
      answer: 1,
      explanation: '洋蔥、大蒜、巧克力、葡萄、酒精與含木糖醇食品對貓有毒，人類鹹食與調味料也應避免。',
      articleSlug: 'diet-guide',
    },
    {
      id: 'c2',
      question: '幫金吉拉轉換新飼料，正確的做法是？',
      options: ['直接整碗換新的', '用 7–10 天新舊混合逐步過渡', '餓牠一天再給新飼料', '新舊各放一碗讓牠自己選'],
      answer: 1,
      explanation: '換食需 7–10 天過渡，新舊比例從 1:3 → 1:1 → 3:1 漸進，並觀察食慾與糞便。',
      articleSlug: 'diet-guide',
    },
    {
      id: 'c3',
      question: '金吉拉不愛主動喝水，最好的補水策略是？',
      options: ['在水裡加糖吸引牠', '安排濕食並使用流動式飲水機', '強制用針筒餵水', '不用管，貓本來就不用喝水'],
      answer: 1,
      explanation: '每週 2–3 次以上濕食直接從食物補水，搭配流動飲水機與多個水點；水分不足與泌尿道、腎臟問題相關。',
      articleSlug: 'diet-guide',
    },
    {
      id: 'c4',
      question: '成年金吉拉的餵食方式，下列何者較理想？',
      options: ['整天吃到飽不限量', '一日 2–3 餐定時定量', '一天一大餐', '想到才餵'],
      answer: 1,
      explanation: '金吉拉動態偏靜、容易發胖，成貓建議一日 2–3 餐定時定量，依體重調整份量。',
      articleSlug: 'diet-guide',
    },
    {
      id: 'c5',
      question: '一般情況下，金吉拉的梳毛頻率建議是？',
      options: ['每月一次就好', '每週至少 3–4 次，梅雨季更頻繁', '只在換毛期梳', '長毛貓不需要梳毛'],
      answer: 1,
      explanation: '每週至少 3–4 次；台灣梅雨季與換毛期建議每天或隔天一次，濕氣會讓毛更容易打結。',
      articleSlug: 'grooming-guide',
    },
    {
      id: 'c6',
      question: '發現金吉拉毛髮打了小結，第一步該怎麼做？',
      options: ['用力把結扯開', '從結的外側往內用手指或梳尖慢慢挑鬆', '立刻整片剃掉', '用水沖濕再拉'],
      answer: 1,
      explanation: '小結從外側往內慢慢挑鬆、切勿硬拉；頑固結用圓頭剪與皮膚平行修剪；大面積氈化交給專業美容師。',
      articleSlug: 'grooming-guide',
    },
    {
      id: 'c7',
      question: '金吉拉洗澡的合理頻率大約是？',
      options: ['每天洗', '每週洗兩次', '1–2 個月一次甚至更久', '一生都不能洗'],
      answer: 2,
      explanation: '室內貓髒污有限，1–2 個月一次即可；過度清洗反而破壞皮膚油脂，抗拒水的貓可用乾洗產品。',
      articleSlug: 'grooming-guide',
    },
    {
      id: 'c8',
      question: '幫金吉拉洗完澡後，最重要的步驟是？',
      options: ['讓牠自然風乾', '徹底吹乾到底層毛', '馬上餵罐頭', '噴人用香水'],
      answer: 1,
      explanation: '台灣濕度高，半乾的底層毛容易悶出皮膚問題，務必徹底吹乾。',
      articleSlug: 'grooming-guide',
    },
    {
      id: 'c9',
      question: '金吉拉的淚痕日常護理，正確做法是？',
      options: ['每天用溫水棉片輕拭眼周', '用人的卸妝棉沾卸妝水擦', '淚痕是正常的，完全不用理', '直接把眼周毛剃光'],
      answer: 0,
      explanation: '每天溫水棉片輕拭（一眼一片），頑固淚痕搭配貓用眼周清潔液；淚量突增或紅腫則是就醫訊號。',
      articleSlug: 'grooming-guide',
    },
    {
      id: 'c10',
      question: '夏天發現金吉拉張口呼吸、持續喘氣，應該？',
      options: ['正常現象，貓跟狗一樣會喘', '先觀察一週', '盡快降溫並就醫，這對貓是異常訊號', '餵冰塊就好'],
      answer: 2,
      explanation: '貓咪張口呼吸、持續喘氣是異常訊號，扁臉的金吉拉在悶熱環境風險更高，室內建議維持 24–26°C。',
      articleSlug: 'health-overview',
    },
    {
      id: 'c11',
      question: '預防長毛貓毛球症的「三件組」是？',
      options: ['勤梳毛、化毛輔助、充足飲水', '剃毛、斷食、大量零食', '洗澡、曬太陽、喝牛奶', '吃草、吃魚、吃肉'],
      answer: 0,
      explanation: '勤梳毛從源頭減量、化毛膏或化毛配方幫助排出、充足飲水促進腸道蠕動。',
      articleSlug: 'health-overview',
    },
    {
      id: 'c12',
      question: '關於金吉拉的居住環境濕度，建議維持在？',
      options: ['30% 以下越乾越好', '50–60%', '80% 以上保濕', '濕度不影響貓咪'],
      answer: 1,
      explanation: '室內濕度 50–60% 最舒適；台灣潮濕，除濕機對長毛貓幾乎是剛需。',
      articleSlug: 'newbie-checklist',
    },
    {
      id: 'c13',
      question: '購買金吉拉幼貓時，最應該要求繁殖業者提供的檢測是？',
      options: ['智力測驗', 'PKD（多囊腎）基因檢測', '毛色鑑定書', '星座命盤'],
      answer: 1,
      explanation: '波斯家族有 PKD 遺傳傾向，要求 PKD 基因檢測或親貓腎臟超音波報告是唯一的源頭把關。',
      articleSlug: 'buying-adoption-guide',
    },
    {
      id: 'c14',
      question: '依台灣法規，幼貓至少要滿幾週才能離開母貓？',
      options: ['4 週', '8 週', '16 週', '沒有規定'],
      answer: 1,
      explanation: '法規下限為 8 週，12 週更理想；過早離乳影響幼貓健康與社會化。',
      articleSlug: 'buying-adoption-guide',
    },
    {
      id: 'c15',
      question: '剛把金吉拉接回家的第一週，最好的相處方式是？',
      options: ['立刻抱著不放建立感情', '邀朋友來熱鬧迎接', '給牠安靜的單一房間慢慢適應，不強迫互動', '馬上幫牠洗澡除味'],
      answer: 2,
      explanation: '金吉拉慢熱，前幾天讓牠在安全基地觀察環境，用固定作息與零食慢慢建立信任。',
      articleSlug: 'newbie-checklist',
    },
  ],
}

export const banks = { master: masterBank, careExam: careExamBank }
